uploads = []
generated = []

[[outputs]]
id = "gUaRy3kz1o7Gji1A0Kqig"
uri = "file://ascend-os.tar.gz"
type = "unspecified"
title = "ascend-os.tar.gz"

[[outputs]]
id = "UfTonLcBUAQ_4FB2l8m9T"
uri = "file://exports/ascend-os.zip"
type = "unspecified"
title = "Ascend OS — source code"

[[outputs]]
id = "QEsuVjpBtge5-Uhycb_Xg"
uri = "file://exports/ascend-os-source.zip"
type = "unspecified"
title = "Ascend OS — Source Code (80 MB, no videos)"

[[outputs]]
id = "-OuO4Zh0dkN1b1H6CzaAn"
uri = "file://exports/ascend-os-full.zip"
type = "unspecified"
title = "Ascend OS — full app (with videos and assets)"
