// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding-home/HighContrastBold.tsx": () => import("../components/mockups/onboarding-home/HighContrastBold.tsx"),
  "./components/mockups/onboarding-home/SoftMinimal.tsx": () => import("../components/mockups/onboarding-home/SoftMinimal.tsx"),
  "./components/mockups/onboarding-home/WarmGrounded.tsx": () => import("../components/mockups/onboarding-home/WarmGrounded.tsx")
};
