// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/concept-home/ChronologicalFeed.tsx": () => import("../components/mockups/concept-home/ChronologicalFeed.tsx"),
  "./components/mockups/concept-home/ConversationalCoach.tsx": () => import("../components/mockups/concept-home/ConversationalCoach.tsx"),
  "./components/mockups/concept-home/RadarMap.tsx": () => import("../components/mockups/concept-home/RadarMap.tsx"),
  "./components/mockups/concept-home/TerminalMode.tsx": () => import("../components/mockups/concept-home/TerminalMode.tsx"),
  "./components/mockups/onboarding-home/HighContrastBold.tsx": () => import("../components/mockups/onboarding-home/HighContrastBold.tsx"),
  "./components/mockups/onboarding-home/SoftMinimal.tsx": () => import("../components/mockups/onboarding-home/SoftMinimal.tsx"),
  "./components/mockups/onboarding-home/WarmGrounded.tsx": () => import("../components/mockups/onboarding-home/WarmGrounded.tsx"),
  "./components/mockups/surprise-home/DawnDusk.tsx": () => import("../components/mockups/surprise-home/DawnDusk.tsx"),
  "./components/mockups/surprise-home/RitualCard.tsx": () => import("../components/mockups/surprise-home/RitualCard.tsx"),
  "./components/mockups/surprise-home/VoidOrb.tsx": () => import("../components/mockups/surprise-home/VoidOrb.tsx"),
  "./components/mockups/usability-home/AccessibleReadable.tsx": () => import("../components/mockups/usability-home/AccessibleReadable.tsx"),
  "./components/mockups/usability-home/AffordanceFirst.tsx": () => import("../components/mockups/usability-home/AffordanceFirst.tsx"),
  "./components/mockups/usability-home/ClearHierarchy.tsx": () => import("../components/mockups/usability-home/ClearHierarchy.tsx")
};
